pipeline {
    agent any
    stages {
        stage('Build Docker Images') {
            steps {
                sh 'docker\u002dcompose build'
            }
        }
        stage('Run Containers') {
            steps {
                sh 'docker\u002dcompose up -d'
            }
        }
    }
}
